fix invalid response id after closing file
openssh-rust/openssh-sftp-client pull request #77
Opened 2023-05-13 09:19 UTC by silver-ymz

Sometimes after closing file, the server will send success message later. At this time, if we have removed `response_id` from `SharedData`, it will raise the error of `invalid_response_id`.

2023-05-13 10:35 UTC, NobodyXu commented
Thank you for the PR!

This is an short sight in the openssh-sftp-client, where I didn't think of this.

There's actually another fix for this:

In openssh-sftp-client, [src/handle.rs](https://github.com/openssh-rust/openssh-sftp-client/blob/e11a8dc7bbdc6197d00d94a97fb36e9e118eae56/src/handle.rs#L22), it drops the id right after sending a close request.

This is the culprit, you could change the Drop to wait for the close request by using tokio::spawn.

It will infer additional cost but IMHO might be better than ignoring any id-not-found related STATUS response.

2023-05-13 10:52 UTC, NobodyXu commented
@silver-ymz Can you please test this against the PR in opendal?

2023-05-13 10:53 UTC, NobodyXu commented
BTW, @silver-ymz do you want to become a maintainer of this crate?

2023-05-13 10:54 UTC, NobodyXu requested changes
And please update the doc for "mod unreleased" in src/changelog.rs

2023-05-13 11:09 UTC, silver-ymz commented
> @silver-ymz Can you please test this against the PR in opendal?

I will begin to make commit in opendal soon.

> BTW, @silver-ymz do you want to become a maintainer of this crate?

Thank you for giving me this chance. I'd like to become a maintainer. Sometimes because of my studies I may not be able to deal with issues in time, but I will try to maintain it as much as possible.

2023-05-13 12:03 UTC, NobodyXu commented
> I will begin to make commit in opendal soon.

#thumb_up

> Thank you for giving me this chance. I'd like to become a maintainer.

I've invited you to become a maintainer of openssh-sftp-client, openssh-sftp-protocol, concurrent_arena and awaitable github repository.

@silver-ymz Please also provide me with your crates.io account name.

Also, if you'd like, I can ask jonhoo to invite you to the openssh-rust org, so that you can contribute to every repository under it.

> Sometimes because of my studies I may not be able to deal with issues in time, but I will try to maintain it as much as possible.

That's not a problem, everyone has their own life, just enjoy and contribute when you have time.

Having another maintainer will also reduce the bus-factor of this project while also making updates/improvements more frequent/easier, and all of this is volunteer work/hobbies, I am actually grateful that you are willing to step up and become a maintainer.

2023-05-13 12:03 UTC, NobodyXu approved these changes

2023-05-13 12:07 UTC, merged

2023-05-13 12:08 UTC, NobodyXu commented
Will do a release later today.

2023-05-13 12:37 UTC, NobodyXu commented
@jonhoo Can you please invite @silver-ymz to the openssh-rust org so that they have rw access (or even maintainer access) to all crates?

Thank you!

2023-08-06 11:36 UTC, jonhoo commented
@NobodyXu invited! :tada:

2023-08-06 11:46 UTC, NobodyXu commented
Thank you!